# Generated by Django 4.2.5 on 2023-09-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='text',
            new_name='content',
        ),
    ]
