# Generated by Django 4.2.5 on 2023-09-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_text_content_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Topic',
        ),
    ]
